EffectiveWorkerWeb/EffectiveWorkerWeb/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Models/Project.cs
using System;
using System.Collections.Generic;

namespace WebApplication
{
    public partial class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Premium { get; set; }
        public int? WorkerId { get; set; }

        public virtual Worker Worker { get; set; }
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Models/Worker.cs
using System;
using System.Collections.Generic;

namespace WebApplication
{
    public partial class Worker
    {
        public Worker()
        {
            Projects = new HashSet<Project>();
        }

        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronimic { get; set; }
        public int Seniority { get; set; }

        public virtual ICollection<Project> Projects { get; set; }
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Controllers/ProjectsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationContext _db;
        
        public ProjectsController(ApplicationContext db) {
            _db = db;
        }
        
        public ActionResult Show() {
            return View(_db.Projects.Include(p => p.Worker).ToList());
        }
        
        [HttpGet]
        public ActionResult Add() {
            var workersData = _db.Workers.Include(w => w.Projects).ToList();
            var workers = new SelectList(workersData, "Id", "Surname");
            ViewBag.Workers = workers;
            return View();
        }

        [HttpPost]
        public ActionResult Add(Project project) {
            _db.Projects.Add(project);
            _db.SaveChanges();
            return Redirect("/projects/show");
        }
        
        [HttpGet]
        public ActionResult Edit(int? id) {
            if (id == null) return NotFound();
            var project = _db.Projects.Find(id);
            if (project != null) return View(project);
            return NotFound();
        }

        [HttpPost]
        public ActionResult Edit(Project project) {
            _db.Entry(project).State = EntityState.Modified;
            _db.SaveChanges();
            return Redirect("/projects/show");
        }
        
        [HttpGet]
        public ActionResult Delete(int? id) {
            if (id == null) return NotFound();
            var project = _db.Projects.Find(id);
            if (project == null) return NotFound();
            return View(project);
        }

        [HttpPost, ActionName("delete")]
        public ActionResult DeleteConfirmed(int id) {
            var project = _db.Projects.Find(id);
            if (project == null) return NotFound();
            _db.Entry(project).State = EntityState.Deleted;
            _db.SaveChanges();
            return Redirect("/projects/show");
        }
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Controllers/WorkersController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Controllers
{
    public class WorkersController : Controller
    {
        private readonly ApplicationContext _db;
        
        public WorkersController(ApplicationContext db) {
            _db = db;
        }
        
        public IActionResult Show() {
         var workers = _db.Workers.Include(w => w.Projects);
            return View(workers);
        }   
        
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Add(Worker worker) {
            _db.Add(worker);
            _db.SaveChanges();
            return Redirect("/workers");
        }
        
        [HttpGet]
        public ActionResult Edit(int? id) {
            if (id == null) return NotFound();
            var worker = _db.Workers.Find(id);
            if (worker != null) return View(worker);
            return NotFound();
        }

        [HttpPost]
        public ActionResult Edit(Worker worker) {
            _db.Entry(worker).State = EntityState.Modified;
            _db.SaveChanges();
            return Redirect("/workers/show");
        }
        
        [HttpGet]
        public ActionResult Delete(int? id) {
            if (id == null) return NotFound();
            var worker = _db.Workers.Find(id);
            if (worker == null) return NotFound();
            return View(worker);
        }
        
        [HttpPost, ActionName("delete")]
        public ActionResult DeleteConfirmed(int id) {
            var worker = _db.Workers.Find(id);
            if (worker == null) return NotFound();
            _db.Entry(worker).State = EntityState.Deleted;
            _db.SaveChanges();
            return Redirect("/workers");
        }
    }
}

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Projects/Add.cshtml
@model Project
@{
    ViewBag.Title = "Adding project";
    Layout = "_Layout";
}

<h2>Adding project</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Create"/>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Projects/Delete.cshtml
@model Project
@{
    ViewBag.Title = "Delete worker";
    Layout = "_Layout";
}
<h2>Delete worker @Model.Name</h2>
<dl>
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    
    <dt>Price</dt>
    <dd>@Html.DisplayFor(model => model.Premium)</dd>
</dl>
<form method="post" action="">
    <p><input type="submit" value="Delete"/></p>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Projects/Edit.cshtml
@model Project
@{
    ViewBag.Title = "Editing project";
    Layout = "_Layout";
}

<h2>Editing project "@Model.Name"</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Submit"/>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Projects/Show.cshtml
@model IEnumerable<Project>

@{
    ViewBag.Title = "Projects";
    Layout = "_Layout";
}

<div>
    <h3>Projects</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Price</td>
            <td>Owner</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var project in Model) {
            <tr>
                <td>@project.Id</td>
                <td>@project.Name</td>
                <td>@project.Premium</td>
                <td>@project.Worker.Surname @project.Worker.Name @project.Worker.Patronimic</td>
                <td>
                    <form action="/projects/edit/@project.Id">
                        <input type="submit" value="Edit"/>
                    </form>
                </td>
                <td>
                    <form action="/projects/delete/@project.Id">
                        <input type="submit" value="Delete"/>
                    </form>
                </td>
            </tr>
        }
    </table>
    <p>
        <form action="/projects/add">
            <input type="submit" value="Add project"/>
        </form>
    </p>
</div>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EffectiveWorker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EffectiveWorker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Show">Workers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Show">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019  - A.Voloshina - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Workers/Add.cshtml
@model Worker

@{
    ViewBag.Title = "Adding worker";
    Layout = "_Layout";
}

<h2>Adding worker</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Create"/>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Workers/Delete.cshtml
@model Worker
@{
    ViewBag.Title = "Delete worker";
    Layout = "_Layout";
}
<h2>Delete worker @Model.Name @Model.Surname</h2>
<dl>
    <dt>Surname</dt>
    <dd>@Html.DisplayFor(model => model.Surname)</dd>
    
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    
    <dt>Patronymic</dt>
    <dd>@Html.DisplayFor(model => model.Patronimic)</dd>
    
    <dt>Seniority</dt>
    <dd>@Html.DisplayFor(model => model.Seniority)</dd>
</dl>
<form method="post" action="">
    <p><input type="submit" value="Delete"/></p>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Workers/Edit.cshtml
@model Worker
@{
    ViewBag.Title = "Editing worker";
    Layout = "_Layout";
}

<h2>Editing worker @Model.Name @Model.Surname</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Edit"/>
</form>

EffectiveWorkerWeb/EffectiveWorkerWeb/Views/Workers/Show.cshtml
@model IEnumerable<Worker>
@{
    Layout = "_Layout";
    ViewBag.Title = "Workers";
}
<div>
    <h3>Workers</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Surname</td>
            <td>Name</td>
            <td>Patronymic</td>
            <td>Seniority</td>
            <td>Projects</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var worker in Model) {
            <tr>
                <td>@worker.Id</td>
                <td>@worker.Surname</td>
                <td>@worker.Name</td>
                <td>@worker.Patronimic</td>
                <td>@worker.Seniority</td>
                <td>
                    <ul>
                        @foreach (var project in worker.Projects) {
                            <li>@project.Name</li>
                        }
                    </ul>
                </td>
                <td>
                    <form action="/workers/edit/@worker.Id">
                        <input type="submit" value="Edit"/>
                    </form>
                </td>
                <td>
                    <form action="/workers/delete/@worker.Id">
                        <input type="submit" value="Delete"/>
                    </form>
                </td>
            </tr>
        }
    </table>
    <p>
        <form action="/workers/add">
            <input type="submit" value="Add worker"/>
        </form>
    </p>
</div>